## EXPERIMENT 2
## NUMERICAL PYTHON (NUMPY)

#### NORMALIZATION PROBLEM

In [18]:
#Import numpy library
import numpy as np

# Create a 10x10 array of squares of the first 100 positive integers
A = np.arange(1, 101).reshape(10, 10) ** 2

# Find elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save as div_by_3.npy and print result
np.save('div_by_3.npy', div_by_3)
print (div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


#### DIVISIBLE BY 3 PROBLEM

In [2]:
#Import numpy library
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Normalize the array
X_normalized = (X - mean_X) / std_X

# Save as X_normalized.npy and print result
np.save('X_normalized.npy', X_normalized)
print (X_normalized)


[[-1.23004098 -1.1592348  -0.66233009  1.38551819  0.54058964]
 [-0.51957115  1.0209526  -1.61483815 -0.0347223   1.06892496]
 [ 0.59002676 -1.20154564  0.71895445  0.4640629   0.96047266]
 [ 1.37563198 -1.7573068   0.55723691 -0.71422508  1.4686953 ]
 [ 0.2673449  -1.30750049  0.41611655 -0.97590024  0.34268792]]
