## EXPERIMENT 2
## NUMERICAL PYTHON (NUMPY)

#### NORMALIZATION PROBLEM

In [2]:
#Import numpy library
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Normalize the array
X_normalized = (X - mean_X) / std_X

# Save as X_normalized.npy and print result
np.save('X_normalized.npy', X_normalized)
print (X_normalized)


[[ 0.3144396  -1.35584379 -0.05836655  0.84040653 -1.59941881]
 [-1.19196145 -0.27187549  1.3366232  -1.02546507  1.07938297]
 [ 0.69458329 -1.65445585  0.54644043  0.16301288  1.33720915]
 [-1.263856   -1.52499503  1.15856334  0.49532756  1.3142837 ]
 [-0.44683251  0.67048611  0.88240754 -0.53747674  0.09738098]]


#### DIVISIBLE BY 3 PROBLEM

In [2]:
#Import numpy library
import numpy as np

# Create a 10x10 array of squares of the first 100 positive integers
A = np.arange(1, 101).reshape(10, 10) ** 2

# Find elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save as div_by_3.npy and print result
np.save('div_by_3.npy', div_by_3)
print (A)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
