## EXPERIMENT 2
## NUMERICAL PYTHON (NUMPY)

#### NORMALIZATION PROBLEM

In [2]:
#Import numpy library
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Normalize the array
X_normalized = (X - mean_X) / std_X

# Save as X_normalized.npy and print result
np.save('X_normalized.npy', X_normalized)
print (X_normalized)


[[ 0.3144396  -1.35584379 -0.05836655  0.84040653 -1.59941881]
 [-1.19196145 -0.27187549  1.3366232  -1.02546507  1.07938297]
 [ 0.69458329 -1.65445585  0.54644043  0.16301288  1.33720915]
 [-1.263856   -1.52499503  1.15856334  0.49532756  1.3142837 ]
 [-0.44683251  0.67048611  0.88240754 -0.53747674  0.09738098]]


#### DIVISIBLE BY 3 PROBLEM

In [5]:
#Import numpy library
import numpy as np

# Create a 10x10 array of squares of the first 100 positive integers
A = np.arange(1, 101).reshape(10, 10) ** 2

# Find elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save as div_by_3.npy and print result
np.save('div_by_3.npy', div_by_3)
print (div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
