## EXPERIMENT 2
## NUMERICAL PYTHON (NUMPY)

#### NORMALIZATION PROBLEM

In [18]:
#Import numpy library
import numpy as np

# Create a 10x10 array of squares of the first 100 positive integers
A = np.arange(1, 101).reshape(10, 10) ** 2

# Find elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save as div_by_3.npy and print result
np.save('div_by_3.npy', div_by_3)
print (div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


#### DIVISIBLE BY 3 PROBLEM

In [20]:
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation
mean_X = X.mean()
std_X = X.std()

# Normalize the array
X_normalized = (X - mean_X) / std_X

# Save as X_normalized.npy and print result
np.save('X_normalized.npy', X_normalized)
print (X_normalized)


[[ 1.680798   -0.54201061 -0.72309795  1.51477708 -0.63109677]
 [ 0.22431914  0.95387664  0.43673768 -0.29438905  1.93900515]
 [-0.76546436  1.25863664 -0.76185799 -1.33618297  1.52956681]
 [-0.99348229  0.18261024 -0.19196432  0.49326358  0.64605321]
 [-1.287169   -1.04191543 -1.16292716 -0.97854673 -0.14953953]]
